class SeedExamples < ActiveRecord::Migration[6.0]
  def up
    Wk::Example.create!(japanese: "彼は{貯金}を{増やした|増やす}", english: "he added to his savings")
    Wk::Example.create!(japanese: "これは{家庭}の{収入}を{増やした|増やす}", english: "this has increased family income")
    Wk::Example.create!(japanese: "彼は{体重}が{増えている|増える}", english: "he is putting on weight")
    Wk::Example.create!(japanese: "彼女の{家族}が{一人}{増えた|増える}。", english: "there was a new addition to her family")
    Wk::Example.create!(japanese: "{飛行機}は{速度}を{増した|増す}", english: "the plane increased speed")
    Wk::Example.create!(japanese: "ご{指示}ありがとうございます、{助かりました|助かる}", english: "thank you for your instruction, it really helped")
    Wk::Example.create!(japanese: "{助けて|助ける}！", english: "help me! (I'm going to die; implies urgency)")
    Wk::Example.create!(japanese: "老婦人が{渡る}のを{助けた|助ける}", english: "I helped an old lady across")
    Wk::Example.create!(japanese: "{料理}をするのを{手伝って|手伝う}よ", english: "please help me cook")
    Wk::Example.create!(japanese: "来て{手伝って|手伝う}下さい", english: "come and help us")
    Wk::Example.create!(japanese: "{忙しければ|忙しい}、私が{手伝います|手伝う}", english: "if you are busy, I will help you")
    Wk::Example.create!(japanese: "この{新聞}は{購読}者が{多い}", english: "this paper has a large circulation")
    Wk::Example.create!(japanese: "うちは{朝日}{新聞}と読売{新聞}を{購読しています|購読する}", english: "we take the Asahi and Yomiuri")
    Wk::Example.create!(japanese: "{時計}の{具合}が{悪い}", english: "something is the matter with my watch")
    Wk::Example.create!(japanese: "{風邪}の{具合}はどうですか", english: "how's your cold?")
    Wk::Example.create!(japanese: "{母}はとても{具合}が{悪い}", english: "my mother is seriously ill")
    Wk::Example.create!(japanese: "彼女は{今日}はずっと{具合}がいい", english: "she is heaps better today")
    Wk::Example.create!(japanese: "私がアメリカに{行っている|行く}と{仮定して|仮定}ください", english: "suppose I had gone to America")
    Wk::Example.create!(japanese: "それが{真実}であると{仮定}しよう", english: "let's suppose it's true")
    Wk::Example.create!(japanese: "彼は{最後}の{決心}をする{過程}に{合った|合う}", english: "he was in the process of making a final decision")
    Wk::Example.create!(japanese: "彼はボート作りの{過程}を{説明}した", english: "he explained the process of building a boat")
    Wk::Example.create!(japanese: "その{過程}を彼に{説明}した", english: "I explained the process to him")
    Wk::Example.create!(japanese: "僕は{仕事}より{家庭}の方が{大事}だ", english: "my family comes before my career")
    Wk::Example.create!(japanese: "{夫}は{家}を作り、{妻}は{家庭}を{作る}", english: "men make houses, women make homes")
    Wk::Example.create!(japanese: "{犯人}は{誰}だ？", english: "who's the culprit?")
    Wk::Example.create!(japanese: "{僕}は{犯人}じゃない", english: "I'm not the culprit")
    Wk::Example.create!(japanese: "{自分}を{信じて|信じる}", english: "trust yourself")
    Wk::Example.create!(japanese: "Ａ「彼女はいますか」Ｂ「{自分}はいます」C「いないです」", english: 'A "Do you have a girlfriend?" B "Me, yes" C "No"')
    Wk::Example.create!(japanese: "彼女は{優秀}な{学生}だ", english: "she is an excellent student")
    Wk::Example.create!(japanese: "彼の{兄}はとても{優秀}な{医者}だ", english: "his brother is a very capable doctor")
    Wk::Example.create!(japanese: "この{任務}は{すべて|全て}の任務に{優先}する", english: "this duty has priority over all others")
    Wk::Example.create!(japanese: "AとBを{反応}させるとCが生成されます", english: "C is formed by reacting A with B")
    Wk::Example.create!(japanese: "{報告}書に{対する}彼らの{反応}はどうでしたか", english: "what was their reaction to the report?")
    Wk::Example.create!(japanese: "彼は私が{送った|送る}{合図}に{反応}した。", english: "he responded to the signal I gave")
    Wk::Example.create!(japanese: "{優しい}インターネット", english: "friendly internet")
    Wk::Example.create!(japanese: "{優しい}{人}です", english: "he is kind")
    Wk::Example.create!(japanese: "{美人}ではありませんでしたが、{大きくて|大きい}{やさしい|優しい}{茶色}の{目}をしていて、{かわい|可愛い}らしい{笑顔}でした。", english: "she wasn't beautiful, but she had big, kind brown eyes and a sweet smile")
    Wk::Example.create!(japanese: "つい{先ほど|先程}{君}の{お父さん}に{会いました|会う}", english: "I met your father just now")
    Wk::Example.create!(japanese: "僕は{妻}を{選ぶ}のに{大変}な{間違い}をした", english: "I made a big mistake in choosing my wife")
    Wk::Example.create!(japanese: "あの{事件}は{大統領}の{失態}であった", english: "that incident was a black mark against the president")
    Wk::Example.create!(japanese: "彼を{正直}者だと{信じた|信じる}のは{大間違い}だった", english: "in believing him to be an honest man, I was seriously in error")
    Wk::Example.create!(japanese: "{平和}会談は{再度}{失敗}した", english: "the peace talks failed again")
    Wk::Example.create!(japanese: "万一{失敗}しても、もう一度{がんばります|頑張る}", english: "should I fail, I would try again")
    Wk::Example.create!(japanese: "その{動き}は{大失敗}だった", english: "that move was a big mistake")
    Wk::Example.create!(japanese: "その{大失敗}をやった{とき|時}彼女は何をしていたのか", english: "what was she doing when she made that blunder")
    Wk::Example.create!(japanese: "僕はよく{弟}と{間違えられる|間違える}", english: "I am often mistaken for my brother")
    Wk::Example.create!(japanese: "彼女は私を{妹}と{間違えた|間違える}", english: "she mistook me for my sister")
    Wk::Example.create!(japanese: "彼女は私を{兄}と{間違えた|間違える}", english: "she took me for my brother")
    Wk::Example.create!(japanese: "{不人気}だから{安い}", english: "because it's unpopular it's cheap")
    Wk::Example.create!(japanese: "彼女は{他}の{女の子}達に{人気}があります", english: "she is popular with other girls")
    Wk::Example.create!(japanese: "彼女は{昔}からずっと{人気}のある{女優}でした", english: "she has always been a popular actress")
    Wk::Example.create!(japanese: "彼女は{若い}{とき|時}、とても{人気}があった", english: "when young, she was very popular")
    Wk::Example.create!(japanese: "彼女は{学生}の{間}で{たいへん|大変}{人気}がある", english: "she is very popular among the students")
    Wk::Example.create!(japanese: "母は{事故}の{現場}を{見て|見る}{意識}を{失った|失う}", english: "my mother blacked out on seeing the scene of the accident")
    Wk::Example.create!(japanese: "彼女は{意識}を{回復した|回復する}", english: "she recovered her senses")
    Wk::Example.create!(japanese: "彼らには{罪}の{意識}がない", english: "they have no sense of sin")
    Wk::Example.create!(japanese: "彼は彼女の{存在}を{意識}した", english: "he was conscious of her presence")
    Wk::Example.create!(japanese: "母は彼女に{美しい}{人形}をか{買って|買う}やった。", english: "mother bought a beautiful doll for her")
    Wk::Example.create!(japanese: "彼女は{人形}を{作っています|作る}か", english: "is she making a doll?")
    Wk::Example.create!(japanese: "彼女は{人形}で{遊んでいる|遊ぶ}", english: "she is playing with a doll")
    Wk::Example.create!(japanese: "彼女は私に{かわいい|可愛い}{人形}をくれた", english: "she gave me a pretty doll")
    Wk::Example.create!(japanese: "彼女に{人形}を{作って|作る}あげた", english: "I made her a doll")
    Wk::Example.create!(japanese: "彼女に{人形}をあげなさい", english: "give her a doll")
    Wk::Example.create!(japanese: "{和食}のレストランへ{行く}たびに、{割り箸}を{家}へもって{帰ります|帰る}", english: "whenever I go to a Japanese restaurant, I take the disposable chopsticks home with me")
    Wk::Example.create!(japanese: "僕は君の{健康}を{心配している|心配する}んだ", english: "I am concerned for your health")
    Wk::Example.create!(japanese: "{父}は{健康}を{回復した|回復する}", english: "father recovered his health")
    Wk::Example.create!(japanese: "{鳥}は{本能}的に{飛ぶ}ことを{覚える}", english: "birds learn to fly by instinct")
    Wk::Example.create!(japanese: "{基本的}な{本能}は{消える}ことはない", english: "fundamental instincts will not go away")
    Wk::Example.create!(japanese: "{都合}の良い{とき|時}に{来てく|来る}ださい", english: "please come and see me whenever it is convenient for you")
    Wk::Example.create!(japanese: "RubyWorld Conference 2019プログラムが{公開}されました", english: "the RubyWorld Conference 2019 program has been released")
    Wk::Example.create!(japanese: "彼の{話し方}は{たいへん|大変}{洗練}されている", english: "his speech is very refined")
    Wk::Example.create!(japanese: "{洗練}された{日本語}", english: "polished Japanese")
    Wk::Example.create!(japanese: "彼女は彼の{招待|招待する}を{断った|断る}", english: "she turned down his invitation")
    Wk::Example.create!(japanese: "{名古屋}は{城}で{有名}な{都市}だ", english: "Nagoya is a city which is famous for its castle")
    Wk::Example.create!(japanese: "キンポウゲ{姫}の{奇妙}な{結婚}{物語}", english: "princess Buttercup's bizarre marriage story")
    Wk::Example.create!(japanese: "彼女は{奇妙}な{夢}を{見た|見る}", english: "she dreamed a strange dream")
    Wk::Example.create!(japanese: "彼は{奇妙}な{事}を{考えていた|考える}", english: "he was thinking strange thoughts")
    Wk::Example.create!(japanese: "彼の{話}は、{奇妙}だが、{信じられる|信じる}", english: "his story is strange, but it's believable")
    Wk::Example.create!(japanese: "彼の{行動}は{時々}{奇妙}だ", english: "his behaviour is sometimes strange")
    Wk::Example.create!(japanese: "それは{奇妙}な{動き}だった", english: "that was a strange move")
    Wk::Example.create!(japanese: "両{地域}は{宗教}と{文化}が{違っている|違う}", english: "the two regions differ in religion and culture")
    Wk::Example.create!(japanese: "{町}の{他}の{地域}では争いが{続いた|続く}", english: "in other areas of the city, fighting continued")
    Wk::Example.create!(japanese: "彼女は{禁煙}{区域}を広げたいと{思っている|思う}", english: "she wants to extend the no-smoking area")
    Wk::Example.create!(japanese: "彼はロンドンの{貧しい}{地区}に{住んでいる|住む}", english: "he lives in a poor district of London")
    Wk::Example.create!(japanese: "ジョンは関東{地区}、そして太郎は{関西}{地区}を{担当}している", english: "John covers the Kanto area and Taro covers the Kansai area")
    Wk::Example.create!(japanese: "この{地区}には書店が{少ない}", english: "there are few bookstores in this area")
    Wk::Example.create!(japanese: "この{地区}をよく{知っています|知る}か", english: "are you familiar with this area?")
  end

  def down
    Wk::Example.destroy_all
  end
end
